#!/bin/sh

notify-send "Rsync backup has started";

rsync -av --delete /media/shared/FAKS/ /home/luka/Documents/FAKS/
if [ "$?" -eq "0" ]; then
    notify-send "Backup to SSD finished successfully!";
else
    notify-send "ERROR while backing up to SSD!";
fi

rsync -av /media/shared/FAKS/ /media/storage/BACKUP/FAKS/
if [ "$?" -eq "0" ]; then
    notify-send "Backup to HDD finished successfully!";
else
    notify-send "ERROR while backing up to HDD!";
fi

notify-send "Rsync backup has finished";
