#!/bin/sh
# A rofi -dmenu binary prompt script.
# Gives a rofi -dmenu prompt labeled with $1 to perform command $2.
# For example:
# `./yes-no "Do you want to shutdown?" "shutdown -h now"`

# Original author of this script is Luke Smith from lukesmith.xyz

[ "$(printf "No\\nYes" | rofi -dmenu -i -p "$1" -nb darkred -sb red -sf white -nf gray )" = "Yes" ] && $2
